project:
  type: "website"


website:
  title: "The _N_-Factor Community"
  repo-url: "https://github.com/mfisher87/n-factor-community"
  repo-actions:
    - "edit"
    - "source"
    - "issue"

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy;"

  sidebar:
    background: "#eee"
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: "index.md"
      - text: "Factors"
        href: "factors.md"


format:
  html:
    theme: "cosmo"
    css: "styles.css"
    toc: true
